// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace ReclaimGameplayTags
{
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Vanguard);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Ranger);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Engineer);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Warden);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Vanguard_Dash);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Vanguard_KineticBarrier);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ranger_TacticalScan);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ranger_MagRailLeap);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Engineer_RepairDrone);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Engineer_Overclock);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warden_PurificationPulse);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warden_StabilityField);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Combat);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Movement);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Deploy);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Scan);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Channel);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Shielded);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Downed);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reviving);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Redeploying);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CannotFire);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CannotUseAbility);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Marked);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Overclocked);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StabilityField);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Kinetic);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Electric);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Explosive);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Kinetic);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Electric);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Dash);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Defense);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Device);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build_Survival);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Crawler);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Spitter);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Brute);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Elite);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Armored);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ranged);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mission_Active);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mission_Complete);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mission_Failed);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mission_Extracting);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Alloy);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Crystal);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Biopolymer);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Anomaly);

	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Hostile);
	RECLAIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Purifiable);
}
